version: '2'
services:
  web:
    build: ./web
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes_from:
      - app
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf

  app:
    build: ./app
    depends_on:
      - db
    volumes:
      - ./app/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./app/wordpress/wp-config.php:/var/www/html/wp-config.php
      - ../themes/_s:/var/www/html/wp-content/themes/_s

  db:
    image: mysql:5.7.19
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql.dump.sql:/docker-entrypoint-initdb.d/install_wordpress.sql
      - db-data:/var/lib/mysql

volumes:
  db-data:
